export const ApiErrorCode = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  JWT_ERROR: 'JWT_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  APP_DATA: 'APP_DATA',
  NOT_UNIQUE: 'NOT_UNIQUE',
  FIELD_INVALID_EMPTY: 'FIELD_INVALID_EMPTY',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
} as const;