export const LANGUAGES = {
  ar: "ar_AE",
  en: "en_US",
  cs: "cs_CZ",
  de: "de_DE",
  el: "el_GR",
  es: "es_ES",
  fr: "fr_FR",
  hu: "hu_HU",
  id: "id_ID",
  it: "it_IT",
  ja: "ja_JP",
  ko: "ko_KR",
  pl: "pl_PL",
  pt: "pt_BR",
  ro: "ro_RO",
  ru: "ru_RU",
  th: "th_TH",
  tr: "tr_TR",
  vi: "vi_VN",
  zh: "zh_CN",
};
